//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OrganizationAdmins = newOrganizationAdminsTable("public", "organization_admins", "")

type organizationAdminsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	CreatedAt      postgres.ColumnTimestampz
	OrganizationID postgres.ColumnString
	UserID         postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type OrganizationAdminsTable struct {
	organizationAdminsTable

	EXCLUDED organizationAdminsTable
}

// AS creates new OrganizationAdminsTable with assigned alias
func (a OrganizationAdminsTable) AS(alias string) *OrganizationAdminsTable {
	return newOrganizationAdminsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrganizationAdminsTable with assigned schema name
func (a OrganizationAdminsTable) FromSchema(schemaName string) *OrganizationAdminsTable {
	return newOrganizationAdminsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrganizationAdminsTable with assigned table prefix
func (a OrganizationAdminsTable) WithPrefix(prefix string) *OrganizationAdminsTable {
	return newOrganizationAdminsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrganizationAdminsTable with assigned table suffix
func (a OrganizationAdminsTable) WithSuffix(suffix string) *OrganizationAdminsTable {
	return newOrganizationAdminsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrganizationAdminsTable(schemaName, tableName, alias string) *OrganizationAdminsTable {
	return &OrganizationAdminsTable{
		organizationAdminsTable: newOrganizationAdminsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newOrganizationAdminsTableImpl("", "excluded", ""),
	}
}

func newOrganizationAdminsTableImpl(schemaName, tableName, alias string) organizationAdminsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		UserIDColumn         = postgres.StringColumn("user_id")
		allColumns           = postgres.ColumnList{IDColumn, CreatedAtColumn, OrganizationIDColumn, UserIDColumn}
		mutableColumns       = postgres.ColumnList{CreatedAtColumn, OrganizationIDColumn, UserIDColumn}
	)

	return organizationAdminsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		CreatedAt:      CreatedAtColumn,
		OrganizationID: OrganizationIDColumn,
		UserID:         UserIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
