//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Projects struct {
	ID             uuid.UUID `sql:"primary_key" json:"id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Name           string    `json:"name"`
	Description    *string   `json:"description,omitempty"`
	Slug           string    `json:"slug"`
	OrganizationID uuid.UUID `json:"organization_id"`
}
