//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type TeamLeaders struct {
	ID           uuid.UUID `sql:"primary_key" json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	TeamID       uuid.UUID `json:"team_id"`
	TeamMemberID uuid.UUID `json:"team_member_id"`
}
